app:
  security:
    jwt:
      secret-key: "your_secure_jwt_secret_key_at_least_32_characters_long"
      expiration-ms: 86400000  # 24시간
      refresh-expiration-ms: 604800000  # 7일

admin:
  auth:
    email: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}