app:
  security:
    jwt:
      secret-key: "your_secure_jwt_secret_key_at_least_32_characters_long"
      expiration-ms: 86400000  # 24시간
      refresh-expiration-ms: 604800000  # 7일

    public-paths:
      - /
      - /public/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /h2-console/**
      - /favicon.ico
      - /error
      - /v3/api-docs/**
      - /favicon.ico
      - /actuator/**
      - /admin/**
      - /app/**
      - /common/**

admin:
  auth:
    login-id: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}